"""Seed data ported from the frontend (frontend/src/lib/seed.ts).

Keys are camelCase to match the frontend TypeScript types across the API.
"""


def seed_data() -> dict:
    return {
        "currentUser": {
            "id": "u1",
            "name": "Omar Haddad",
            "email": "omar@northwind.dev",
            "avatarColor": "#6366f1",
        },
        "invites": [],
        "company": {
            "name": "Northwind Labs",
            "workspace": "northwind",
            "hasQA": True,
        },
        "members": [
            {"id": "u1", "name": "Omar Haddad", "email": "omar@northwind.dev", "role": "Developer", "avatarColor": "#6366f1", "status": "Active", "assignedBugs": 5, "resolvedBugs": 34, "lastActive": "2m ago"},
            {"id": "u2", "name": "Sara Nasser", "email": "sara@northwind.dev", "role": "QA", "avatarColor": "#06b6d4", "status": "Active", "assignedBugs": 8, "resolvedBugs": 12, "lastActive": "15m ago"},
            {"id": "u3", "name": "Lena Fischer", "email": "lena@northwind.dev", "role": "Admin", "avatarColor": "#f59e0b", "status": "Active", "assignedBugs": 0, "resolvedBugs": 3, "lastActive": "1h ago"},
            {"id": "u4", "name": "Marcus Reed", "email": "marcus@northwind.dev", "role": "Developer", "avatarColor": "#10b981", "status": "Active", "assignedBugs": 4, "resolvedBugs": 27, "lastActive": "3h ago"},
            {"id": "u5", "name": "Priya Shah", "email": "priya@northwind.dev", "role": "Developer", "avatarColor": "#3b82f6", "status": "Active", "assignedBugs": 6, "resolvedBugs": 41, "lastActive": "Yesterday"},
            {"id": "u6", "name": "Tomas Vidal", "email": "tomas@northwind.dev", "role": "QA", "avatarColor": "#ef4444", "status": "Invited", "assignedBugs": 0, "resolvedBugs": 0, "lastActive": "—"},
        ],
        "projects": [
            {
                "id": "p1",
                "name": "E-Commerce Platform",
                "description": "Online marketplace for customers to browse, purchase, and track orders across web and mobile.",
                "purpose": "Provide a fast, reliable checkout and catalog experience with support for promotions, saved carts, and multi-currency payments.",
                "type": "Web Application",
                "frontend": ["React", "TypeScript", "Tailwind CSS", "Vite"],
                "backend": ["FastAPI", "Python"],
                "database": ["MongoDB", "PyMongo"],
                "services": ["Stripe", "Algolia", "SendGrid"],
                "auth": ["JWT", "bcrypt"],
                "deployment": ["Vercel", "AWS ECS"],
                "architecture": "Modular monolith with a REST API gateway and background workers.",
                "modules": ["Catalog", "Cart", "Checkout", "Orders", "Payments", "Notifications"],
                "apiPatterns": "REST with resource-based routes, cursor pagination, idempotency keys on writes.",
                "environments": {
                    "development": "localhost + Docker Compose",
                    "staging": "staging.shop.northwind.dev",
                    "production": "shop.northwind.dev",
                },
                "browsers": ["Chrome", "Firefox", "Safari", "Edge"],
                "platforms": ["Web", "iOS Safari", "Android Chrome"],
                "businessRules": [
                    {"id": "br1", "title": "Empty carts cannot be checked out", "description": "The checkout endpoint must reject any request where the cart contains zero line items and return a 422 with a clear error."},
                    {"id": "br2", "title": "Discounts never exceed order subtotal", "description": "Applied promotions and store credit combined can reduce the total to a minimum of 0, never negative."},
                    {"id": "br3", "title": "Inventory is reserved at payment intent", "description": "Stock is decremented when a payment intent is created and released after 15 minutes if not captured."},
                ],
                "testingTools": ["Pytest", "Playwright", "Postman", "Vitest"],
                "conventions": "PEP 8 for Python, ESLint + Prettier for TS, conventional commits.",
                "constraints": "p95 checkout latency under 800ms. No breaking API changes without versioning.",
                "repoUrl": "https://github.com/northwind/ecommerce-platform",
                "docsUrl": "https://docs.northwind.dev/ecommerce",
                "memberIds": ["u1", "u2", "u4", "u5", "u3"],
                "openBugs": 12,
                "highSeverity": 3,
                "resolvedBugs": 48,
                "awaitingValidation": 2,
                "updatedAt": "2h ago",
            },
            {
                "id": "p2",
                "name": "Insights Analytics API",
                "description": "Backend service that aggregates product usage events and exposes reporting endpoints for dashboards.",
                "purpose": "Deliver near real-time analytics with reliable event ingestion and low-latency aggregation queries.",
                "type": "API / Backend",
                "frontend": [],
                "backend": ["FastAPI", "Python", "Celery"],
                "database": ["MongoDB", "Redis"],
                "services": ["Kafka", "AWS S3"],
                "auth": ["JWT", "API Keys"],
                "deployment": ["AWS EKS"],
                "architecture": "Event-driven microservices with a streaming ingestion pipeline.",
                "modules": ["Ingestion", "Aggregation", "Reporting", "Export"],
                "apiPatterns": "REST + async job polling, versioned under /v1.",
                "environments": {
                    "development": "localhost + LocalStack",
                    "staging": "api-staging.northwind.dev",
                    "production": "api.northwind.dev",
                },
                "browsers": [],
                "platforms": ["Server"],
                "businessRules": [
                    {"id": "br1", "title": "Events are idempotent by event_id", "description": "Duplicate events with the same event_id must not be double-counted."},
                ],
                "testingTools": ["Pytest", "Locust", "Postman"],
                "conventions": "PEP 8, typed with mypy, conventional commits.",
                "constraints": "Ingestion must handle 5k events/sec sustained.",
                "repoUrl": "https://github.com/northwind/insights-api",
                "memberIds": ["u1", "u5", "u4"],
                "openBugs": 5,
                "highSeverity": 1,
                "resolvedBugs": 22,
                "awaitingValidation": 1,
                "updatedAt": "Yesterday",
            },
            {
                "id": "p3",
                "name": "Mobile Companion App",
                "description": "Cross-platform mobile app for order tracking, push notifications, and support chat.",
                "purpose": "Give customers a lightweight on-the-go experience tied to their web account.",
                "type": "Mobile Application",
                "frontend": ["React Native", "TypeScript", "Expo"],
                "backend": ["FastAPI", "Python"],
                "database": ["MongoDB"],
                "services": ["Firebase", "Stripe"],
                "auth": ["JWT"],
                "deployment": ["App Store", "Google Play"],
                "architecture": "Client-server with a shared REST API and offline cache.",
                "modules": ["Auth", "Orders", "Notifications", "Support"],
                "apiPatterns": "REST, shared with web platform.",
                "environments": {
                    "development": "Expo Go",
                    "staging": "TestFlight / Internal track",
                    "production": "Public stores",
                },
                "browsers": [],
                "platforms": ["iOS", "Android"],
                "businessRules": [],
                "testingTools": ["Jest", "Detox"],
                "conventions": "ESLint + Prettier, conventional commits.",
                "constraints": "Cold start under 2s on mid-tier devices.",
                "memberIds": ["u2", "u5"],
                "openBugs": 3,
                "highSeverity": 0,
                "resolvedBugs": 9,
                "awaitingValidation": 0,
                "updatedAt": "3d ago",
            },
        ],
        "bugs": [
            {
                "id": "b1042",
                "ref": "#1042",
                "title": "Checkout returns HTTP 500 when cart is empty",
                "description": "When a user reaches the checkout endpoint with an empty cart, the API responds with a 500 Internal Server Error instead of a validation error. This surfaces a generic error screen to customers and pollutes error monitoring.",
                "projectId": "p1",
                "status": "In Progress",
                "severity": "High",
                "priority": "Urgent",
                "category": "Backend",
                "reporterId": "u2",
                "assigneeIds": ["u1"],
                "validatorId": "u2",
                "stepsToReproduce": [
                    "Sign in as any customer with no items in the cart.",
                    "Send a POST request to /v1/checkout with an empty line_items array.",
                    "Observe the response status and payload.",
                ],
                "expectedResult": 'API returns 422 Unprocessable Entity with a clear "cart is empty" message.',
                "actualResult": "API returns 500 Internal Server Error with an unhandled exception trace.",
                "environment": "Staging — staging.shop.northwind.dev",
                "browserDevice": "Chrome 128 / macOS · reproduced on Firefox 129",
                "createdAt": "Sep 14, 2026 · 09:12",
                "updatedAt": "2h ago",
                "evidence": [
                    {"id": "e1", "type": "Console Error", "title": "Browser console output", "content": "POST https://staging.shop.northwind.dev/v1/checkout 500 (Internal Server Error)\n  at CheckoutButton.onClick (checkout.tsx:88)\n  Uncaught (in promise) Error: Request failed with status code 500", "language": "log", "addedBy": "u2", "addedAt": "Sep 14 · 09:14"},
                    {"id": "e2", "type": "API Response", "title": "Response body from /v1/checkout", "content": '{\n  "detail": "Internal Server Error",\n  "trace_id": "b1f3c9a2-7d21-4a0e-9e1a-2f6d8c4b1a90"\n}', "language": "json", "addedBy": "u2", "addedAt": "Sep 14 · 09:15"},
                    {"id": "e3", "type": "Stack Trace", "title": "Server traceback", "content": 'Traceback (most recent call last):\n  File "app/api/checkout.py", line 54, in create_checkout\n    total = sum(item.price * item.qty for item in cart.line_items)\n  File "app/services/pricing.py", line 22, in compute_total\n    subtotal = reduce(lambda a, b: a + b, amounts)\nTypeError: reduce() of empty iterable with no initial value', "language": "python", "addedBy": "u1", "addedAt": "Sep 14 · 10:02"},
                    {"id": "e4", "type": "Relevant Code", "title": "pricing.py — compute_total", "content": "def compute_total(line_items: list[LineItem]) -> Decimal:\n    amounts = [i.price * i.qty for i in line_items]\n    # BUG: reduce with no initial value raises on empty list\n    subtotal = reduce(lambda a, b: a + b, amounts)\n    return apply_discounts(subtotal)", "language": "python", "addedBy": "u1", "addedAt": "Sep 14 · 10:05"},
                    {"id": "e5", "type": "Server Log", "title": "API gateway log excerpt", "content": "2026-09-14T09:12:44Z ERROR checkout trace_id=b1f3c9a2 status=500 path=/v1/checkout user=cust_8821 duration=142ms\n2026-09-14T09:12:44Z ERROR unhandled TypeError in compute_total", "language": "log", "addedBy": "u2", "addedAt": "Sep 14 · 09:20"},
                ],
                "comments": [
                    {"id": "c1", "authorKind": "QA", "authorName": "Sara Nasser", "body": "Bug reproduced on Chrome and Firefox in staging. Happens 100% of the time with an empty cart.", "at": "Sep 14 · 09:22"},
                    {"id": "c2", "authorKind": "System", "authorName": "DevDiagnose", "body": "Bug assigned to Omar Haddad by Sara Nasser.", "at": "Sep 14 · 09:25"},
                    {"id": "c3", "authorKind": "Developer", "authorName": "Omar Haddad", "body": "Confirmed — backend returns 500 when the cart is empty because compute_total reduces an empty list.", "at": "Sep 14 · 10:06"},
                    {"id": "c4", "authorKind": "AI", "authorName": "DevDiagnose AI", "body": "Likely missing validation before checkout processing. reduce() over an empty iterable raises TypeError. Add a guard and an initial value.", "at": "Sep 14 · 10:10"},
                    {"id": "c5", "authorKind": "Developer", "authorName": "Omar Haddad", "body": "Adding an explicit empty-cart guard that returns 422, plus an initial value in the reduce. Writing tests now.", "at": "Sep 14 · 11:40"},
                ],
                "analyses": [
                    {
                        "id": "a1",
                        "version": 1,
                        "model": "Llama 3.1 70B",
                        "generatedAt": "Sep 14, 2026 · 09:40",
                        "contextVersion": "ctx v3 · E-Commerce Platform",
                        "classification": "Backend — unhandled exception on edge-case input",
                        "severityRec": "High",
                        "priorityRec": "Urgent",
                        "rootCause": "The checkout total calculation calls reduce() over the cart line items without an initial value. When the cart is empty the iterable is empty, raising a TypeError that is not caught and surfaces as a 500.",
                        "explanation": 'The server traceback points directly at compute_total in pricing.py, and the relevant code confirms reduce() is used without a seed. Business rule "Empty carts cannot be checked out" requires this path to return a validation error, not a server error. The console and API-response evidence confirm the client receives a 500.',
                        "investigationSteps": [
                            "Reproduce with an empty line_items array against /v1/checkout in staging.",
                            "Confirm the traceback originates in pricing.compute_total.",
                            "Verify no upstream validation rejects empty carts before pricing runs.",
                        ],
                        "suggestedFix": 'Add an explicit empty-cart guard in the checkout handler that returns 422 with a clear message, and give reduce() an initial value of Decimal("0") (or use sum) so pricing is safe for empty inputs.',
                        "recommendedTests": [
                            'Unit test: compute_total([]) returns Decimal("0").',
                            "API test: POST /v1/checkout with empty cart returns 422 and the empty-cart message.",
                            "Regression test: normal cart still checks out with correct total.",
                        ],
                        "confidence": 88,
                        "uncertainty": [
                            "Assumes no other caller depends on compute_total raising on empty input.",
                            "Discount logic downstream was not fully reviewed for empty-subtotal behavior.",
                        ],
                        "evidenceConsidered": ["Stack Trace", "Relevant Code", "API Response", "Console Error"],
                    },
                ],
                "timeline": [
                    {"id": "t1", "kind": "created", "label": "Bug created", "actor": "Sara Nasser", "at": "Sep 14 · 09:12"},
                    {"id": "t2", "kind": "assigned", "label": "Assigned to Omar Haddad", "actor": "Sara Nasser", "at": "Sep 14 · 09:25"},
                    {"id": "t3", "kind": "ai", "label": "AI analysis v1 generated", "actor": "DevDiagnose AI", "at": "Sep 14 · 09:40"},
                    {"id": "t4", "kind": "comment", "label": "Root cause confirmed", "actor": "Omar Haddad", "at": "Sep 14 · 10:06"},
                    {"id": "t5", "kind": "status", "label": "Moved to In Progress", "actor": "Omar Haddad", "at": "Sep 14 · 10:30"},
                ],
            },
            {
                "id": "b1041",
                "ref": "#1041",
                "title": "Product images fail to load on Safari",
                "description": "Catalog images intermittently return broken image icons on Safari due to a CORS misconfiguration on the CDN.",
                "projectId": "p1",
                "status": "Assigned",
                "severity": "Medium",
                "priority": "High",
                "category": "Frontend",
                "reporterId": "u2",
                "assigneeIds": ["u5"],
                "stepsToReproduce": ["Open the catalog on Safari.", "Scroll through product cards.", "Observe broken images."],
                "expectedResult": "All product images render.",
                "actualResult": "Some images show a broken icon.",
                "environment": "Production",
                "browserDevice": "Safari 17 / macOS",
                "createdAt": "Sep 13, 2026 · 14:02",
                "updatedAt": "5h ago",
                "evidence": [],
                "comments": [],
                "analyses": [],
                "timeline": [{"id": "t1", "kind": "created", "label": "Bug created", "actor": "Sara Nasser", "at": "Sep 13 · 14:02"}],
            },
            {
                "id": "b1039",
                "ref": "#1039",
                "title": "Order confirmation email not sent for guest checkout",
                "description": "Guest checkout completes but the confirmation email is never delivered.",
                "projectId": "p1",
                "status": "QA Validation",
                "severity": "High",
                "priority": "High",
                "category": "Backend",
                "reporterId": "u4",
                "assigneeIds": ["u4"],
                "validatorId": "u2",
                "stepsToReproduce": ["Check out as guest.", "Complete payment.", "Check inbox."],
                "expectedResult": "Confirmation email arrives within a minute.",
                "actualResult": "No email is sent.",
                "environment": "Staging",
                "browserDevice": "Chrome 128 / Windows",
                "createdAt": "Sep 12, 2026 · 11:20",
                "updatedAt": "1d ago",
                "evidence": [],
                "comments": [],
                "analyses": [],
                "timeline": [{"id": "t1", "kind": "created", "label": "Bug created", "actor": "Marcus Reed", "at": "Sep 12 · 11:20"}],
            },
            {
                "id": "b1038",
                "ref": "#1038",
                "title": "Slow aggregation query on large date ranges",
                "description": "Reporting endpoint times out when the requested range exceeds 90 days.",
                "projectId": "p2",
                "status": "Submitted",
                "severity": "Critical",
                "priority": "Urgent",
                "category": "Performance",
                "reporterId": "u5",
                "assigneeIds": [],
                "stepsToReproduce": ["Request /v1/reports with a 120-day range.", "Observe timeout."],
                "expectedResult": "Report returns within 3s.",
                "actualResult": "Request times out at 30s.",
                "environment": "Production",
                "browserDevice": "Server",
                "createdAt": "Sep 15, 2026 · 08:05",
                "updatedAt": "30m ago",
                "evidence": [],
                "comments": [],
                "analyses": [],
                "timeline": [{"id": "t1", "kind": "created", "label": "Bug created", "actor": "Priya Shah", "at": "Sep 15 · 08:05"}],
            },
            {
                "id": "b1035",
                "ref": "#1035",
                "title": "JWT refresh token not rotated on login",
                "description": "On re-login the refresh token is reused instead of rotated, weakening session security.",
                "projectId": "p1",
                "status": "Resolved",
                "severity": "High",
                "priority": "High",
                "category": "Security",
                "reporterId": "u2",
                "assigneeIds": ["u1"],
                "validatorId": "u2",
                "stepsToReproduce": ["Log in twice.", "Compare refresh tokens."],
                "expectedResult": "Refresh token rotates on each login.",
                "actualResult": "Same refresh token is returned.",
                "environment": "Staging",
                "browserDevice": "Chrome 128",
                "createdAt": "Sep 10, 2026 · 16:40",
                "updatedAt": "2d ago",
                "evidence": [],
                "comments": [],
                "analyses": [],
                "timeline": [{"id": "t1", "kind": "created", "label": "Bug created", "actor": "Sara Nasser", "at": "Sep 10 · 16:40"}],
            },
            {
                "id": "b1031",
                "ref": "#1031",
                "title": "Cart quantity can be set to a negative number",
                "description": "The quantity stepper allows negative values which break totals.",
                "projectId": "p1",
                "status": "Closed",
                "severity": "Low",
                "priority": "Medium",
                "category": "UI/UX",
                "reporterId": "u2",
                "assigneeIds": ["u5"],
                "validatorId": "u2",
                "stepsToReproduce": ["Open cart.", "Click minus below 1."],
                "expectedResult": "Quantity cannot go below 1.",
                "actualResult": "Quantity goes negative.",
                "environment": "Production",
                "browserDevice": "Chrome",
                "createdAt": "Sep 8, 2026 · 10:15",
                "updatedAt": "4d ago",
                "evidence": [],
                "comments": [],
                "analyses": [],
                "timeline": [{"id": "t1", "kind": "created", "label": "Bug created", "actor": "Sara Nasser", "at": "Sep 8 · 10:15"}],
            },
            {
                "id": "b1029",
                "ref": "#1029",
                "title": "Push notifications delayed by several minutes",
                "description": "Order status push notifications arrive 5–10 minutes late.",
                "projectId": "p3",
                "status": "In Progress",
                "severity": "Medium",
                "priority": "Medium",
                "category": "Performance",
                "reporterId": "u5",
                "assigneeIds": ["u5"],
                "stepsToReproduce": ["Update an order status.", "Wait for push."],
                "expectedResult": "Push within 30s.",
                "actualResult": "Push after several minutes.",
                "environment": "Production",
                "browserDevice": "iOS 18",
                "createdAt": "Sep 11, 2026 · 13:00",
                "updatedAt": "6h ago",
                "evidence": [],
                "comments": [],
                "analyses": [],
                "timeline": [{"id": "t1", "kind": "created", "label": "Bug created", "actor": "Priya Shah", "at": "Sep 11 · 13:00"}],
            },
        ],
        "notifications": [
            {"id": "n1", "category": "Assignment", "message": "Bug #1042 was assigned to you.", "at": "2h ago", "read": False, "bugRef": "#1042"},
            {"id": "n2", "category": "Validation", "message": "Bug #1039 is awaiting QA validation.", "at": "5h ago", "read": False, "bugRef": "#1039"},
            {"id": "n3", "category": "AI", "message": "AI analysis completed for Bug #1042.", "at": "5h ago", "read": True, "bugRef": "#1042"},
            {"id": "n4", "category": "System", "message": "Marcus commented on Bug #1032.", "at": "Yesterday", "read": True, "bugRef": "#1032"},
            {"id": "n5", "category": "AI", "message": "New evidence added to Bug #1042 — re-analysis suggested.", "at": "Yesterday", "read": True, "bugRef": "#1042"},
            {"id": "n6", "category": "Assignment", "message": "Bug #1038 is unassigned and marked Critical.", "at": "30m ago", "read": False, "bugRef": "#1038"},
        ],
        "recentActivity": [
            {"id": "r1", "message": "Sara assigned Bug #1042 to Omar", "at": "2h ago"},
            {"id": "r2", "message": "AI analysis generated for Bug #1042", "at": "5h ago"},
            {"id": "r3", "message": "Bug #1039 moved to QA Validation", "at": "1d ago"},
            {"id": "r4", "message": "Sara resolved Bug #1024", "at": "2d ago"},
            {"id": "r5", "message": "Priya opened Bug #1038 (Critical)", "at": "30m ago"},
        ],
    }


def current_bug_ref(bugs: list[dict]) -> str:
    """Return the next bug id/ref (e.g. b1043 / #1043) based on seeded or existing bugs."""
    max_num = 1042
    for b in bugs:
        ref = b.get("ref", "")
        digits = "".join(ch for ch in ref if ch.isdigit())
        if digits:
            max_num = max(max_num, int(digits))
    return f"b{max_num + 1}", f"#{max_num + 1}"